# Databricks notebook source
# MAGIC %md
# MAGIC **1. Load the supermarket_invoice_data.csv file into a PySpark DataFrame and display the first 5 rows of the DataFrame.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **2. Filter all invoices where the payment method is "Credit Card" and retrieve all invoices where the total price is greater than $500.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **3. Calculate the total revenue generated by each store and find the average unit price of products sold in each store.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **4. a)Group the data by Customer_ID and calculate the total quantity purchased by each customer.**
# MAGIC
# MAGIC **b)Group the data by Product_ID and find the maximum and minimum Total_Price for each product.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **5. Use a window function to calculate the cumulative total price for each customer and rank products based on their total sales in descending order.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **6. Extract the year and month from the Invoice_Date column and calculate the number of days since the invoice date for each row.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **7. Convert the Total_Price from USD to IND using a conversion rate of 1 USD = 83 IND.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **8. Pivot the invoice data to show the total quantity purchased by each customer for each product.**

# COMMAND ----------



# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **9. Calculate the total sales and average unit price for each payment method.**

# COMMAND ----------

#Paste your Answer here

# COMMAND ----------

# MAGIC %md
# MAGIC **10. Find out which product is the most popular based on the total quantity sold.**

# COMMAND ----------

#Paste your Answer here
